name: "+ Update aqua user list"
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  update-list:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - id: token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{secrets.APP_ID_AQUAPROJ_AQUA}}
          private-key: ${{secrets.APP_PRIVATE_KEY_AQUAPROJ_AQUA}}
          permission-pull-requests: write
          permission-contents: write

      - run: |
          set -euo pipefail
          go run ./cmd/list-aqua-users | tee docs/LIST.md
        env:
          GITHUB_TOKEN: ${{github.token}}

      - run: cat docs/HEADER.md docs/LIST.md docs/FOOTER.md > README.md

      - uses: suzuki-shunsuke/commit-action@06e3b49d4706498d325d29bd85adc82ecf2f5d8f # v1.0.0
        with:
          branch: update-list-${{github.run_id}}
          commit_message: "docs: update the user list"

      - run: |
          set -eu
          url=$(gh pr create -t "docs: update the user list" -H "$BRANCH" -b "$BODY")
          gh pr merge "$url" -s --auto
        env:
          BRANCH: update-list-${{github.run_id}}
          GH_TOKEN: ${{steps.token.outputs.token}}
          BODY: |
            This pull request is created by [GitHub Actions](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}).
